<!-- jQuery  -->
<script src="../js/lib/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="../js/lib/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="../js/lib/metisMenu.min.js"></script>

<!-- datetimepicker -->
<script src="../js/lib/bootstrap-datetimepicker.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="../js/lib/startmin.js"></script>

<!-- seajs -->
<script src="../js/lib/sea.js"></script>
<script src="../js/common.js"></script>