  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="http://222.196.35.229:8000/">LExam V3.0</a>
      
        <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="http://222.196.35.229:8000/exam/5/#">
              <i class="icon-user"></i> 教师
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">  
              <li><a href="http://222.196.35.229:8000/user/logout/">登出</a></li>
            </ul>
        </div>
      
        <div class="nav-collapse">
          
  <ul class="nav">
    <li id="nav_home"><a href="http://222.196.35.229:8000/">主页</a></li>
            
    <li id="nav_exam" class="active">
        <a href="http://222.196.35.229:8000/exam/5/">题目列表</a>
    </li>
    <li id="nav_submits">
        <a href="http://222.196.35.229:8000/exam/5/submits/">我的提交</a>
    </li>     
    <li id="nav_faqs"><a href="http://222.196.35.229:8000/faqs/">FAQs</a></li>
    </ul>
          
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>