<!-- jQuery  -->
<script src="../js/lib/jquery.min.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="../js/lib/bootstrap.min.js"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="../js/lib/metisMenu.min.js"></script>

<!-- datetimepicker -->
<script src="../js/lib/bootstrap-datetimepicker.min.js"></script>

<!-- Custom Theme JavaScript -->
<script src="../js/lib/startmin.js"></script>

<!-- seajs -->
<script src="../js/lib/sea.js"></script>
<script>
seajs.config({
    base : '../js/',
    alias : {
        jquery: "lib/jquery.min.js",
        ui: "ui",
        biz: "biz",
        paginator : 'lib/jqPaginator.js',
        artTemplate : 'lib/artTemplate.js',
        bootstrap : 'lib/bootstrap.min.js',
        ueditor_config : 'lib/ueditor/ueditor.config.js',
        ueditor: 'lib/ueditor/ueditor.all.min.js',
        metisMenu: 'lib/metisMenu.min.js',
        datetimepicker: 'lib/bootstrap-datetimepicker.min.js',
        startmin: 'lib/startmin.js'
    }
});
</script>
<script src="../js/common.js"></script>