define(function(require){
    return {
        PROBLEM_LIST: '../../mock/problem.json',
        EXAM_LIST: '../../mock/exam.json',
        PROBLEM_DELETE: '../../mock/result.json',
        EXAM_DELETE: '../../mock/result.json',
        SELECTKNOWLEDGE: '../../mock/selectKnowLedge.json',
        SELECT_KNOWLEDGE: '../../mock/selectKnows.json',
        INSERT_KNOWLEDGE: '../../mock/result.json',
        DELETE_KNOWLEDGE: '../../mock/result.json',
        INSERT_PROBLEM: '../../mock/insertProblem.json',
        SELECT_PROBLEM: '../../mock/selectProblem.json',
        UPDATE_PROBLEM: '../../mock/result.json',
        SELECT_SITEINFO: '../../mock/selectSiteInfo.json',
        SELECT_PROFILE: '../../mock/selectProfile.json',
        SELECT_PRO_BYID: '../../mock/selectProById.json',
        SELECT_EXAM_BYID: '../../mock/selectExamById.json',
        INSERT_EXAM: '../../mock/result.json',
        UPDATE_EXAM: '../../mock/result.json',
        DELETEPROFILE: '../../mock/result.json',
        UPDATE_PROFILE: '../../mock/result.json',
        INSERT_PROFILE: '../../mock/result.json',
        MAJOR_LIST: '../../mock/majorList.json',
        SELECT_MAJOR: '../../mock/majorList.json',
        DELETE_MAJOR: '../../mock/result.json',
        ADD_MAJOR: '../../mock/result.json',
        UPDATE_MAJOR: '../../mock/result.json',
        LOGIN: '../../mock/loginResult.json',
        SELECT_SUBMIT: '../../mock/usersubmit.json',
        UNLOCKLIST: '../../mock/unlocklist.json',
        UNLOCKIT: '../../mock/result.json',
        SELECT_PAPERLIST: '../../mock/paperList.json',
        DELETE_PAPER: '../../mock/result.json',
        SELECT_PAPERDETAIL: '../../mock/paperDetail.json',
        SELECT_SIMILARITYLIST: '../../mock/similarityList.json'
    }
})